// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: balance.sql

package db

import (
	"context"
)

const createBalance = `-- name: CreateBalance :one
INSERT INTO balance (
        budget_id,
        user_id,
        capital,
        eatout,
        entertainment
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING balance_id, budget_id, user_id, capital, eatout, entertainment, total, created_at
`

type CreateBalanceParams struct {
	BudgetID      int64  `json:"budget_id"`
	UserID        int64  `json:"user_id"`
	Capital       string `json:"capital"`
	Eatout        string `json:"eatout"`
	Entertainment string `json:"entertainment"`
}

func (q *Queries) CreateBalance(ctx context.Context, arg CreateBalanceParams) (Balance, error) {
	row := q.db.QueryRowContext(ctx, createBalance,
		arg.BudgetID,
		arg.UserID,
		arg.Capital,
		arg.Eatout,
		arg.Entertainment,
	)
	var i Balance
	err := row.Scan(
		&i.BalanceID,
		&i.BudgetID,
		&i.UserID,
		&i.Capital,
		&i.Eatout,
		&i.Entertainment,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const selectBalance = `-- name: SelectBalance :one
SELECT balance_id, budget_id, user_id, capital, eatout, entertainment, total, created_at
FROM balance
WHERE user_id = $1
    AND budget_id = $2
`

type SelectBalanceParams struct {
	UserID   int64 `json:"user_id"`
	BudgetID int64 `json:"budget_id"`
}

func (q *Queries) SelectBalance(ctx context.Context, arg SelectBalanceParams) (Balance, error) {
	row := q.db.QueryRowContext(ctx, selectBalance, arg.UserID, arg.BudgetID)
	var i Balance
	err := row.Scan(
		&i.BalanceID,
		&i.BudgetID,
		&i.UserID,
		&i.Capital,
		&i.Eatout,
		&i.Entertainment,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const updateBalance = `-- name: UpdateBalance :one
UPDATE balance
SET capital = capital + $1,
    eatout = eatout + $2,
    entertainment = entertainment + $3
WHERE user_id = $4
    AND budget_id = $5
RETURNING balance_id, budget_id, user_id, capital, eatout, entertainment, total, created_at
`

type UpdateBalanceParams struct {
	Capital       string `json:"capital"`
	Eatout        string `json:"eatout"`
	Entertainment string `json:"entertainment"`
	UserID        int64  `json:"user_id"`
	BudgetID      int64  `json:"budget_id"`
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (Balance, error) {
	row := q.db.QueryRowContext(ctx, updateBalance,
		arg.Capital,
		arg.Eatout,
		arg.Entertainment,
		arg.UserID,
		arg.BudgetID,
	)
	var i Balance
	err := row.Scan(
		&i.BalanceID,
		&i.BudgetID,
		&i.UserID,
		&i.Capital,
		&i.Eatout,
		&i.Entertainment,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const updateCapitalBalance = `-- name: UpdateCapitalBalance :one
UPDATE balance
SET capital = $1
WHERE user_id = $2 AND budget_id = $3
RETURNING balance_id, budget_id, user_id, capital, eatout, entertainment, total, created_at
`

type UpdateCapitalBalanceParams struct {
	Capital  string `json:"capital"`
	UserID   int64  `json:"user_id"`
	BudgetID int64  `json:"budget_id"`
}

func (q *Queries) UpdateCapitalBalance(ctx context.Context, arg UpdateCapitalBalanceParams) (Balance, error) {
	row := q.db.QueryRowContext(ctx, updateCapitalBalance, arg.Capital, arg.UserID, arg.BudgetID)
	var i Balance
	err := row.Scan(
		&i.BalanceID,
		&i.BudgetID,
		&i.UserID,
		&i.Capital,
		&i.Eatout,
		&i.Entertainment,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const updateEatoutBalance = `-- name: UpdateEatoutBalance :one
UPDATE balance
SET eatout = $1
WHERE user_id = $2 AND budget_id = $3
RETURNING balance_id, budget_id, user_id, capital, eatout, entertainment, total, created_at
`

type UpdateEatoutBalanceParams struct {
	Eatout   string `json:"eatout"`
	UserID   int64  `json:"user_id"`
	BudgetID int64  `json:"budget_id"`
}

func (q *Queries) UpdateEatoutBalance(ctx context.Context, arg UpdateEatoutBalanceParams) (Balance, error) {
	row := q.db.QueryRowContext(ctx, updateEatoutBalance, arg.Eatout, arg.UserID, arg.BudgetID)
	var i Balance
	err := row.Scan(
		&i.BalanceID,
		&i.BudgetID,
		&i.UserID,
		&i.Capital,
		&i.Eatout,
		&i.Entertainment,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const updateEntertainmentBalance = `-- name: UpdateEntertainmentBalance :one
UPDATE balance
SET entertainment = $1
WHERE user_id = $2 AND budget_id = $3
RETURNING balance_id, budget_id, user_id, capital, eatout, entertainment, total, created_at
`

type UpdateEntertainmentBalanceParams struct {
	Entertainment string `json:"entertainment"`
	UserID        int64  `json:"user_id"`
	BudgetID      int64  `json:"budget_id"`
}

func (q *Queries) UpdateEntertainmentBalance(ctx context.Context, arg UpdateEntertainmentBalanceParams) (Balance, error) {
	row := q.db.QueryRowContext(ctx, updateEntertainmentBalance, arg.Entertainment, arg.UserID, arg.BudgetID)
	var i Balance
	err := row.Scan(
		&i.BalanceID,
		&i.BudgetID,
		&i.UserID,
		&i.Capital,
		&i.Eatout,
		&i.Entertainment,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}
