// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: balance.sql

package db

import (
	"context"
)

const createBalance = `-- name: CreateBalance :one
INSERT INTO balance (
    budget_id, user_id, capital, eatout,
    entertainment
)   VALUES (
$1, $2, $3, $4, $5
) RETURNING balance_id, budget_id, user_id, capital, eatout, entertainment, total, created_at
`

type CreateBalanceParams struct {
	BudgetID      int64  `json:"budget_id"`
	UserID        int64  `json:"user_id"`
	Capital       string `json:"capital"`
	Eatout        string `json:"eatout"`
	Entertainment string `json:"entertainment"`
}

func (q *Queries) CreateBalance(ctx context.Context, arg CreateBalanceParams) (Balance, error) {
	row := q.db.QueryRowContext(ctx, createBalance,
		arg.BudgetID,
		arg.UserID,
		arg.Capital,
		arg.Eatout,
		arg.Entertainment,
	)
	var i Balance
	err := row.Scan(
		&i.BalanceID,
		&i.BudgetID,
		&i.UserID,
		&i.Capital,
		&i.Eatout,
		&i.Entertainment,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}
