// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"database/sql"
	"time"
)

type Balance struct {
	BalanceID     int64          `json:"balance_id"`
	BudgetID      int64          `json:"budget_id"`
	UserID        int64          `json:"user_id"`
	Capital       string         `json:"capital"`
	Eatout        string         `json:"eatout"`
	Entertainment string         `json:"entertainment"`
	Total         sql.NullString `json:"total"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type Budget struct {
	BudgetID      int64          `json:"budget_id"`
	UserID        int64          `json:"user_id"`
	StartDate     time.Time      `json:"start_date"`
	EndDate       time.Time      `json:"end_date"`
	Savings       string         `json:"savings"`
	Capital       string         `json:"capital"`
	Eatout        string         `json:"eatout"`
	Entertainment string         `json:"entertainment"`
	Income        sql.NullString `json:"income"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type CapitalExpense struct {
	CapitalExpID int64        `json:"capital_exp_id"`
	BudgetID     int64        `json:"budget_id"`
	UserID       int64        `json:"user_id"`
	Expenses     string       `json:"expenses"`
	Description  string       `json:"description"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type EatoutExpense struct {
	EatoutExpID int64        `json:"eatout_exp_id"`
	BudgetID    int64        `json:"budget_id"`
	UserID      int64        `json:"user_id"`
	Expenses    string       `json:"expenses"`
	Description string       `json:"description"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type EntertainmentExpense struct {
	EntertainmentExpID int64        `json:"entertainment_exp_id"`
	BudgetID           int64        `json:"budget_id"`
	UserID             int64        `json:"user_id"`
	Expenses           string       `json:"expenses"`
	Description        string       `json:"description"`
	CreatedAt          sql.NullTime `json:"created_at"`
}

type User struct {
	ID        int64        `json:"id"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
}
