// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"
)

type Querier interface {
	CreateBalance(ctx context.Context, arg CreateBalanceParams) (Balance, error)
	CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBudget(ctx context.Context, arg DeleteBudgetParams) error
	DeleteUser(ctx context.Context, email string) error
	SelectAllBudgets(ctx context.Context, arg SelectAllBudgetsParams) ([]Budget, error)
	SelectSingleBudget(ctx context.Context, arg SelectSingleBudgetParams) (Budget, error)
	SelectUser(ctx context.Context, email string) (User, error)
	UpdateBudget(ctx context.Context, arg UpdateBudgetParams) error
}

var _ Querier = (*Queries)(nil)
