// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: sumExpenses.sql

package db

import (
	"context"
)

const sumCapitalExpenses = `-- name: SumCapitalExpenses :one
SELECT SUM(expenses) FROM capital_expenses
WHERE user_id = $1 AND budget_id = $2
`

type SumCapitalExpensesParams struct {
	UserID   int64 `json:"user_id"`
	BudgetID int64 `json:"budget_id"`
}

func (q *Queries) SumCapitalExpenses(ctx context.Context, arg SumCapitalExpensesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumCapitalExpenses, arg.UserID, arg.BudgetID)
	var sum int64
	err := row.Scan(&sum)
	return sum, err
}

const sumEatoutExpenses = `-- name: SumEatoutExpenses :one
SELECT SUM(expenses) FROM eatout_expenses
WHERE user_id = $1 AND budget_id = $2
`

type SumEatoutExpensesParams struct {
	UserID   int64 `json:"user_id"`
	BudgetID int64 `json:"budget_id"`
}

func (q *Queries) SumEatoutExpenses(ctx context.Context, arg SumEatoutExpensesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumEatoutExpenses, arg.UserID, arg.BudgetID)
	var sum int64
	err := row.Scan(&sum)
	return sum, err
}

const sumEntertainmentExpenses = `-- name: SumEntertainmentExpenses :one
SELECT SUM(expenses) FROM entertainment_expenses
WHERE user_id = $1 AND budget_id = $2
`

type SumEntertainmentExpensesParams struct {
	UserID   int64 `json:"user_id"`
	BudgetID int64 `json:"budget_id"`
}

func (q *Queries) SumEntertainmentExpenses(ctx context.Context, arg SumEntertainmentExpensesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumEntertainmentExpenses, arg.UserID, arg.BudgetID)
	var sum int64
	err := row.Scan(&sum)
	return sum, err
}
